# Generated by Django 5.1 on 2024-08-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArabalarModeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marka_Model', models.CharField(max_length=50)),
                ('Fiyat', models.IntegerField()),
                ('Plaka', models.CharField(max_length=20)),
            ],
        ),
    ]
