# Generated by Django 5.1 on 2024-08-27 12:38

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Galeri', '0002_rename_arabalarmodeli_arabalar'),
    ]

    operations = [
        migrations.AddField(
            model_name='arabalar',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='slug', editable=False, populate_from='Plaka', unique=True),
            preserve_default=False,
        ),
    ]
